projects/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include #- 앱 전용 url은 include로 처리
from pybo.views import base_views

# from pybo import views
# app_name='config'#<- 네임스페이스 설정

#첫 사이트 메인 url
urlpatterns = [
    path('', base_views.mainpage, name='mainpage'), #-> 첫 화면을 pybo의 index로 지정
    path('admin/', admin.site.urls),
    # path('pybo/', views.index),
    #path(url경로, 호출할 뷰 함수)
    path('pybo/', include('pybo.urls')), #-> .../pybo/ETC & .../pybo/ETC2 등 pybo로 시작하는 url을 추가할 때 pybo.urls만 수정하면 됨
    path('common/', include('common.urls')), #common앱 추가
]

handler404 = 'common.views.page_not_found'

projects/mysite/pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'pybo' #네임스페이스 설정

urlpatterns = [
    #메인 pybo 페이지

    #질문 상세 페이지 (상세, 댓글)
    path('board/<str:category>/<int:question_id>/', base_views.detail, name='detail'),

    #===============================================

    #메인페이지 - 카테고리별 게시판
    path('board/<str:category>/', base_views.board, name='board'),

    #카테고리별 질문 작성
    path('board/<str:category>/create/', question_views.category_question_create, name='category_question_create'),

    #카테고리별 질문 삭제
    path('board/<str:category>/delete/<int:question_id>/', question_views.category_question_delete, name='category_question_delete'),

    #카테고리별 질문 수정
    path('board/<str:category>/modify/<int:question_id>/', question_views.category_question_modify, name='category_question_modify'),

    #카테고리별 게시글 처리완료
    path('board/<str:category>/processed/<int:question_id>/', question_views.category_question_processed, name='category_question_processed'),


    #===============================================

    #카테고리별 답변 등록
    path('answer/create/<int:question_id>/<str:category>/', answer_views.category_answer_create, name='category_answer_create'), #답변등록

    #카테고리별 답변 수정
    path('answer/modify/<int:answer_id>/', answer_views.category_answer_modify, name='category_answer_modify'),

    #카테고리별 답변 삭제
    path('answer/delete/<int:answer_id>/', answer_views.category_answer_delete, name='category_answer_delete'),

    #카테고리(pre/find) 정보 추출
    path('board/<str:category>/extract/', base_views.extract_excel, name='extract_excel'),

    #===============================================

    #카테고리별 게시글 추천
    path('question/vote/<int:question_id>/<str:category>/', question_views.category_question_vote, name='category_question_vote'),

    #카테고리별 댓글 추천
    path('answer/vote/<int:answer_id>/', answer_views.category_answer_vote, name='category_answer_vote'),
]

projects/mysite/pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here. -> DB에 저장될 흠.. 테이블? 느낌인듯 col 정의하는 곳
# https://docs.djangoproject.com/en/5.1/ref/models/fields/#field-types -> 데이터 타입 
class Pre_Question(models.Model): #택배 사전 접수
    CATEGORY_CHOICES = [
        ('pre', '택배 사전 접수'),
        ('find', '택배 찾기'),
        ('qna', '문의하기'),
        ('notice', '공지사항'),
    ]
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='pre')

    processed = models.BooleanField(default=False)

    subject = models.CharField(max_length=500, blank=True)
    send_name = models.CharField(max_length=50) #보내는 분 성함
    send_phone = models.CharField(max_length=20) #보내는 분 연락처

    send_addr_zipcode = models.CharField(max_length=200, blank=True, null=True) #보내는 분 - 우편번호
    send_addr_road = models.CharField(max_length=200, blank=True, null=True) #보내는 분 - 도로명 주소
    send_addr_detail = models.CharField(max_length=200, blank=True, null=True) #보내는 분 - 상세 주소

    rec_name = models.CharField(max_length=50) #받는 분 성함
    rec_phone = models.CharField(max_length=20) #받는 분 연락처

    rec_addr_zipcode = models.CharField(max_length=200, blank=True, null=True) #받는 분 - 우편번호
    rec_addr_road = models.CharField(max_length=200, blank=True, null=True) #받는 분 - 도로명 주소
    rec_addr_detail = models.CharField(max_length=200, blank=True, null=True) #받는 분 - 상세 주소

    product_type = models.CharField(max_length=100) #상품 종류
    package_type = models.CharField(max_length=20) #포장 형식
    num = models.CharField(max_length=10) #수량
    pay_method = models.CharField(max_length=50) #지불방식 -> at_now = 선불 // at_delivered = 후불

    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='author_pre_question') #User가 삭제되면 질문도 삭제
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_pre_question') 

    def __str__(self):
        return self.subject





class Find_Question(models.Model):
    processed = models.BooleanField(default=False)

    subject = models.CharField(max_length=200, blank=True)
    send_name = models.CharField(max_length=50) #보내는 분 성함
    send_phone = models.CharField(max_length=20) #보내는 분 연락처

    send_addr_zipcode = models.CharField(max_length=200, blank=True, null=True) #보내는 분 - 우편번호
    send_addr_road = models.CharField(max_length=200, blank=True, null=True) #보내는 분 - 도로명 주소
    send_addr_detail = models.CharField(max_length=200, blank=True, null=True) #보내는 분 - 상세 주소

    product_type = models.CharField(max_length=100) #상품 종류
    package_type = models.CharField(max_length=20) #포장 형식
    num = models.CharField(max_length=10) #수량

    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='author_find_question') #User가 삭제되면 질문도 삭제
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_find_question') 

    def __str__(self):
        return self.subject







class Question(models.Model): #공지 / 질문
    processed = models.BooleanField(default=False)
    
    CATEGORY_CHOICES = [
        ('qna', '문의하기'),
        ('notice', '공지사항'),
    ]
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='qna')

    subject = models.CharField(max_length=200, blank=True)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='author_question') #User가 삭제되면 질문도 삭제
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question') 

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE) #앞의 모델(Question)이 사라지면 댓글도 자동 삭제
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='author_answer') #User가 삭제되면 답변도 삭제
    modify_date = models.DateTimeField(null=True, blank=True)
        #null=True -> DB에 null 허용
        #blank=True -> 추후 form.is_valid()에서 값에 상관없이 검증 통과
        #수정하는 경우는 데이터를 생성할 때가 아닌, 수정할 때만 생기므로 -> null값과 유효성 검사를 통과할 수 있다.
    voter = models.ManyToManyField(User, related_name='voter_answer') 

    def __str__(self):
        title = f'[댓글] {self.question.subject}'
        return title

# class Comment(models.Model):

projects/mysite/pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Pre_Question, Find_Question

PACKAGE_CHOICES = [
    ('naked', '나체'),
    ('box', '박스'),
    ('vinyl', '비닐'),
    ('madae', '마대'),
    ('custom', '직접 입력'),  # 추가!
]

NUM_CHOICES = [
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('custom', '직접 입력'),
]

PAY_METHOD = [
    ('at_now', '현불'),
    ('at_delivered', '착불'),
]

class Pre_QuestionForm(forms.ModelForm):
    package_type = forms.ChoiceField(choices=PACKAGE_CHOICES, label='포장 형식')
    num = forms.ChoiceField(choices=NUM_CHOICES, label='수량')  # 1부터 10까지의 수량 선택지
    pay_method = forms.ChoiceField(choices=PAY_METHOD, label='지불 방식')

    class Meta: #ModelForm에서는 필수
        model = Pre_Question #사용 할 모델
        fields = ['subject', 'send_name', 'send_phone', 'send_addr_zipcode', 'send_addr_road', 'send_addr_detail', 'rec_name', 'rec_phone', 'rec_addr_zipcode', 'rec_addr_road', 'rec_addr_detail', 'product_type', 'package_type', 'num', 'pay_method'] #QuestionForm에서 사용할 Queston 모델의 속성들
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }
        labels = {
            'subject': '제목',
            'send_name': '보내는 분 성함',
            'send_phone': '보내는 분 연락처',
            'send_addr_zipcode': '보내는 분 우편주소',
            'send_addr_road': '보내는 분 도로명 주소',
            'send_addr_detail': '보내는 분 상세 주소',

            'rec_name': '받는 분 성함',
            'rec_phone': '받는 분 연락처',
            'rec_addr_zipcode': '받는 분 우편주소',
            'rec_addr_road': '받는 분 도로명 주소',
            'rec_addr_detail': '받는 분 상세 주소',
            'product_type': '상품 종류',
            'package_type': '포장 형식',
            'num': '수량',
            'pay_method': '지불 방식',
        }  

class Find_QuestionForm(forms.ModelForm):
    package_type = forms.ChoiceField(choices=PACKAGE_CHOICES, label='포장 형식')
    num = forms.ChoiceField(choices=NUM_CHOICES, label='수량') 

    class Meta: #ModelForm에서는 필수
        model = Find_Question #사용 할 모델
        fields = ['subject', 'send_name', 'send_phone', 'send_addr_zipcode', 'send_addr_road', 'send_addr_detail', 'product_type', 'package_type', 'num'] #QuestionForm에서 사용할 Queston 모델의 속성들

        labels = {
            'subject': '제목',
            'send_name': '보내는 분 성함',
            'send_phone': '보내는 분 연락처',
            
            'send_addr_zipcode': '보내는 분 우편주소',
            'send_addr_road': '보내는 분 도로명 주소',
            'send_addr_detail': '보내는 분 상세 주소',
            
            'product_type': '상품 종류',
            'package_type': '포장 형식',
            'num': '수량',
        } 


class QuestionForm(forms.ModelForm):
    class Meta: #ModelForm에서는 필수
        model = Question #사용 할 모델
        fields = ['subject', 'content'] #QuestionForm에서 사용할 Queston 모델의 속성들
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }
        labels = {
            'subject': '제목',
            'content': '내용',
        }  

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

projects/mysite/pybo/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
# from django.http import HttpResponseNotAllowed
from django.utils import timezone
from ..models import Question, Answer
from ..forms import QuestionForm, AnswerForm

from django.core.paginator import Paginator #- 한 페이지에 여러 개의 결과를 보여주는 것 방지
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required(login_url='common:login')
def category_answer_create(request, question_id, category): #답변등록
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user

            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=question.id, category=category), answer.id))
        
    else:
        form = AnswerForm()

    context = {'question': question, 'form': form, 'category': category}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def category_answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    category = answer.question.category

    if request.user == answer.author:
        if request.method == "POST":
            form = AnswerForm(request.POST, instance=answer)
            if form.is_valid():
                answer = form.save(commit=False)
                answer.modify_date = timezone.now()
                answer.save()
                return redirect('{}#answer_{}'.format(
                    resolve_url('pybo:detail', question_id=answer.question.id, category=category), answer.id))
            
        else:
            form = AnswerForm(instance=answer)

        context = {'answer': answer, 'form': form, 'category': category}
        return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def category_answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    category = answer.question.category

    if request.user == answer.author or request.user.is_superuser:
        answer.delete()
        return redirect('pybo:detail', question_id=answer.question.id, category=category)
    
    messages.error(request, '삭제권한이 없습니다')
    return redirect('pybo:detail', question_id=answer.question.id, category=category)

@login_required(login_url='common:login')
def category_answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    category = answer.question.category

    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    else:
        answer.voter.add(request.user)

    return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=answer.question.id, category=category), answer.id))


#===============================================

def answer_create(request, question_id): #답변등록
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user

            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()
    
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user == answer.author:
        if request.method == "POST": #-> GET에서 받아온 HTML 폼 정보를 채운 후 submit 버튼을 눌렀을 때
            form = AnswerForm(request.POST, instance=answer) #기존 answer 정보를 instance로
            if form.is_valid():
                answer = form.save(commit=False)
                answer.modify_date = timezone.now()
                answer.save()
                return redirect('{}#answer_{}'.format(
                    resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
            
        else: #-> GET인 경우 -> 수정하는 HTML 폼 요청
            form = AnswerForm(instance=answer)

        context = {'answer': answer, 'form': form}
        return render(request, 'pybo/answer_form.html', context)
    
    #수정 권한 없는 경우
    messages.error(request, '수정권한이 없습니다')
    return redirect('pybo:detail', question_id=answer.question.id)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user == answer.author or request.user.is_superuser:
        answer.delete()
        return redirect('pybo:detail', question_id=answer.question.id)
    
    messages.error(request, '삭제권한이 없습니다')
    return redirect('pybo:detail', question_id=answer.question.id)

#댓글 추천
@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    else:
        answer.voter.add(request.user)

    return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=answer.question.id), answer.id))

projects/mysite/templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}

<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

projects/mysite/templates/pybo/find_question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">
                <p><strong>보내는 분:</strong> {{ question.send_name }}</p>
                <p><strong>보내는 분 TEL:</strong> {{ question.send_phone }}</p>
                <br>
                <p><strong>보내는 분 우편변호:</strong> {{ question.send_addr_zipcode }}</p>
                <p><strong>보내는 분 도로명 주소:</strong> {{ question.send_addr_road }}</p>
                <p><strong>보내는 분 상세 주소:</strong> {{ question.send_addr_detail }}</p>

                <br><hr><br>
                
                <p><strong>상품 종류:</strong> {{ question.product_type }}</p>
                
                {% if question.package_type == 'madae' %}
                <p><strong>포장 형식:</strong> 마대</p>
                {% elif question.package_type == 'box' %}
                <p><strong>포장 형식:</strong> 박스</p>
                {% elif question.package_type == 'vinyl' %}
                <p><strong>포장 형식:</strong> 비닐</p>
                {% elif question.package_type == 'naked' %}
                <p><strong>포장 형식:</strong> 나체</p>
                {% else %}
                <p><strong>포장 형식:</strong> 기타(직접입력) - {{ question.package_type }}</p>
                {% endif %}

                {% if question.num == '1' %}
                <p><strong>수량:</strong> 1</p>
                {% elif question.num == '2' %}
                <p><strong>수량:</strong> 2</p>
                {% elif question.num == '3' %}
                <p><strong>수량:</strong> 3</p>
                {% elif question.num == '4' %}
                <p><strong>수량:</strong> 4</p>
                {% elif question.num == '5' %}
                <p><strong>수량:</strong> 5</p>
                {% else %}
                <p><strong>수량:</strong> {{ question.num }}</p>
                {% endif %}

            </div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div>작성자: {{ question.author.username }}</div>
                    <div>작성일시: {{ question.create_date }}</div>
                    {% if question.modify_date %}
                    <div>수정일시: {{ question.modify_date }}</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="my-3">

        <!-- 삭제 -->
        {% if request.user == question.author or request.user.is_superuser %}
        <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
        data-uri="{% url 'pybo:category_question_delete' category question.id %}" style="background-color:#FFC6C1;">삭제</a>
        {% endif %}

        <!-- 처리완료 -->
        {% if request.user.is_superuser %}
        <a href="javascript:void(0)" class="processed btn btn-sm btn-outline-secondary"
        data-uri="{% url 'pybo:category_question_processed' category question.id %}" style="background-color:#AFFFC8;">처리완료</a>
        {% endif %}


    </div>

</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});

const processed_elements = document.getElementsByClassName("processed");
Array.from(processed_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("처리완료 진행하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});

</script>
{% endblock %}

projects/mysite/templates/pybo/original_question_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="category" value="{{ category }}">

        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
         
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" readonly class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>

        <div class="mb-3">
            <label for="content" class="form-label">내용 (아래 빈칸을 채워주세요)</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

        <div class="mb-3">
            <label for="id_package_type" class="form-label">포장 형식</label>
            {{ form.package_type }}
        </div>

        <!-- {{ form.as_p }} -->
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

projects/mysite/templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">

    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}

    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ question.content|mark }}</div>
            <div class="d-flex justify-content-end">

                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">[수정일시]</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}

                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    <div class="my-3">

    {% if request.user == question.author or request.user.is_superuser %}
    <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'pybo:category_question_delete' category question.id %}" style="background-color:#FFC6C1;">삭제</a>
    {% endif %}

    <!-- 처리완료 -->
    {% if request.user.is_superuser and question.category == 'qna' %}
    <a href="javascript:void(0)" class="processed btn btn-sm btn-outline-secondary"
    data-uri="{% url 'pybo:category_question_processed' category question.id %}" style="background-color:#AFFFC8;">처리완료</a>
    {% endif %}
    </div>

    <!-- 답변 -->
    <br><br>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a> <!-- 답변 수정 후 다시 돌아올 위치 = 앵커-->
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ answer.content|mark }}</div>
            <div class="d-flex justify-content-end">

                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">[수정일시]</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}

                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            
            <div class="my-3">

                {% if request.user == answer.author or request.user.is_superuser %}
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                data-uri="{% url 'pybo:category_answer_delete' answer.id %}">삭제</a>
                {% endif %}


            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 답변 등록 -->
    <form action="{% url 'pybo:category_answer_create' question.id category %}" method="post" class="my-3">
        {% csrf_token %}
        
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->

        <br><br><br>
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});

const processed_elements = document.getElementsByClassName("processed");
Array.from(processed_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("처리완료 진행하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}